# ubuntuイメージをベースに作成する。
FROM ubuntu
# メンテナンス者
MAINTAINER h.shigemoto <h.shigemoto@pureatio.com>
# Pythonインストール
RUN apt-get update && apt-get install -y python3.5 \
&& apt-get install -y python3.5-dbg \
&& apt-get install -y python3.5-dev \
&& apt-get install -y python3-pip
